[package]
name = "kanban"
version = "6.3.0"
edition = "2024"

[dependencies]
anyhow = "1.0.99"
askama = "0.16.0"
axum = "0.8.9"
rand = "0.10.1"
rusqlite = { version = "0.40.0", features = ["bundled"] }
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.143"
socketioxide = "0.18.3"
tokio = { version = "1.52.3", features = ["rt-multi-thread"] }
tower-http = { version = "0.6.6", features = ["fs"] }
tracing = { version = "0.1.41", features = ["log"] }
tracing-appender = "0.2.3"
tracing-subscriber = { version = "0.3.20", features = ["json"] }
uuid = { version = "1.23.2", features = ["v7"] }

[profile.release]
debug = false
lto = true