[tasks.bundle]
command = "deno"
args = ["task", "build"]

[tasks.build]
command = "cargo"
args = ["build", "--release"]

[tasks.serve]
command = "cargo"
args = ["run"]
env = { KANBAN_CERT = "./certs/kanban-cert.pem", KANBAN_KEY = "./certs/kanban-key.pem" }

[tasks.dev]
dependencies = [
    "bundle",
    "serve",
]